### ISSUE TITLE
beaver and exceptions

### ISSUE THREAD

**Issue by cova-fe** [python-beaver/python-beaver#281]
Hi all,
I noticed a strange behaviour when beaver encounters a problem that raises a python exception. Example: some problems in rabbitmq connection. This can be seen in logs, but afterwards beavers stops working correctly, leaving also some zombie process along the way.
It could be that in some part of the code there is a kind of "catchall" except statement, but before I start digging the code, does someone experienced the same issue?
Thanks.

**Comment by ajoas** [comment]
I've experienced this behavior, specifically with improper redis_url: configs.  My configs are managed with Chef, and if things go wrong with config management, and the redis_url: config line ends up being blank, beaver throws the stacktrace below, over and over.  

Once this happens, only a kill -9 will stop beaver so that you can correct the config and restart.  Normal kills have no effect.

I would also note that I have found in general, if beaver throws errors, it often won't respond to normal kill signals (and thus init script restarts).  I do also find the occasional zombie process, but I don't have an example to paste in at this moment.

Stacktrace:

[2015-11-02 14:04:11,292] INFO    Starting queue consumer
Process Process-1:15:
Traceback (most recent call last):
  File "/opt/beaver/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/beaver/python/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/beaver/python/lib/python2.7/site-packages/beaver/run_queue.py", line 25, in run_queue 
    transport = create_transport(beaver_config, logger=logger)
  File "/opt/beaver/python/lib/python2.7/site-packages/beaver/transports/__init__.py", line 20, in create_transport
    transport = transport_class(beaver_config=beaver_config, logger=logger)
  File "/opt/beaver/python/lib/python2.7/site-packages/beaver/transports/redis_transport.py", line 19, in __init__
    for url in urls.split(','):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by JamieCressey** [comment]
Closing as I think this is fixed by #385. Please upgrade to 36.0.1 and reopen if you're still having problems.
