### ISSUE TITLE
beaver stops when tailing large files

### ISSUE THREAD

**Issue by Bjarke42** [python-beaver/python-beaver#290]
I have a simple setup to send raw json from logfiles via rabbitmq, but beaver seems never to be able to start, so here is my simple debug setup:

beaver config file:
# /etc/beaver/conf

[beaver]
logstash_version: 1
sincedb_path=/root/beaver/since.db

[/xxx/log/traffic.json]
format: raw
tags: nginx

starting beaver as:
beaver -d -c beaver.config

it reads the config file, and ends at the following step:
[2015-01-28 10:11:01,085] INFO    [811g2fc0002] - watching logfile /xxx/log/traffic.json
[2015-01-28 10:11:01,086] DEBUG   [811g2fc0002] - getting start position /xxx/log/traffic.json
[2015-01-28 10:11:01,086] DEBUG   [811g2fc0002] - getting end position for /xxx/log/traffic.json

the process itself is using 100% cpu all the time.

and if i do a ctrl-c on the program to stop it it gives following stack trace:

^C[2015-01-28 10:13:08,981] INFO    SIGINT detected
[2015-01-28 10:13:08,981] INFO    Shutting down. Please wait...
[2015-01-28 10:13:08,983] INFO    SIGINT detected
[2015-01-28 10:13:08,984] INFO    Shutting down. Please wait...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python2.6/dist-packages/beaver/dispatcher/worker.py", line 70, in create_queue_producer
    worker = Worker(beaver_config, queue_consumer_function=create_queue_consumer, callback=queue.put, logger=logger)
  File "/usr/local/lib/python2.6/dist-packages/beaver/worker/worker.py", line 65, in __init__
    self._seek_to_end()
  File "/usr/local/lib/python2.6/dist-packages/beaver/worker/worker.py", line 298, in _seek_to_end
    while data['file'].readline():
  File "/usr/lib/python2.6/io.py", line 1862, in readline
    line += self._get_decoded_chars()
  File "/usr/local/lib/python2.6/dist-packages/beaver/dispatcher/worker.py", line 44, in cleanup
    worker_proc.terminate()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 111, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
[2015-01-28 10:13:08,988] DEBUG   [811g2fc0002] - updating sincedb for logfile /xxx/log/traffic.json from 0 to 0
[2015-01-28 10:13:08,990] INFO    Shutdown complete.

Seems to be stuck in the tail ???
the file being logged grows about a few hundred megabytes an hour. 
How do it get it to consume my logfile ?

**Comment by Bjarke42** [comment]
beaver version is 33.0.0

**Comment by JamieCressey** [comment]
@Bjarke42 is this still an issue? Please try upgrading to 35.0.2 as quite a few changes have been made since 33

**Comment by JamieCressey** [comment]
Closing due to inactivity. PRs are accepted - Feel free to reopen!
