### ISSUE TITLE
Make rawjson fallback to raw

### ISSUE THREAD

**Issue by analytically** [python-beaver/python-beaver#301]
Some tools log their messages as json, but their errors as plain text. So it'd be handy if rawjson would fallback to raq (or string?) in that case.

**Comment by josegonzalez** [comment]
Example?

**Comment by analytically** [comment]
For example, my Sensu client log output:
```
{"timestamp":"2015-03-05T15:49:39.667923+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/base.json"}
{"timestamp":"2015-03-05T15:49:39.668212+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/base.json","changes":{"checks":{"cpu_percent_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/cpu-pcnt-usage-metrics.rb --scheme stats.gauges.:::name:::.cpu","standalone":true,"interval":10,"handlers":["relay"]}],"disk_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/disk-metrics.rb --scheme stats.gauges.:::name:::.disk","standalone":true,"interval":10,"handlers":["relay"]}],"disk_usage_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/disk-usage-metrics.rb --scheme stats.gauges.:::name:::","standalone":true,"interval":10,"handlers":["relay"]}],"entropy_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/entropy-metrics.rb --scheme stats.gauges.:::name:::.entropy","standalone":true,"interval":10,"handlers":["relay"]}],"net_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/net-metrics.rb --scheme stats.gauges.:::name:::.net","standalone":true,"interval":10,"handlers":["relay"]}],"load_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/load-metrics.rb --scheme stats.gauges.:::name:::","standalone":true,"interval":10,"handlers":["relay"]}],"interface_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/interface-metrics.rb --scheme stats.gauges.:::name:::.interface","standalone":true,"interval":10,"handlers":["relay"]}],"vmstat_metrics":[null,{"type":"metric","command":"/etc/sensu/plugins/vmstat-metrics.rb --scheme stats.gauges.:::name:::.vmstat","standalone":true,"interval":10,"handlers":["relay"]}],"entropy_check":[null,{"command":"/etc/sensu/plugins/check-entropy.rb","interval":60,"standalone":true,"handlers":["default"]}],"hardware_fail_check":[null,{"command":"/etc/sensu/plugins/check-hardware-fail.rb","interval":60,"standalone":true,"handlers":["default"]}],"supervisor_check":[null,{"command":"/etc/sensu/plugins/check-supervisor-socket.rb -u buttercoin -p FeYskS2qjP7qvED","interval":10,"standalone":true,"handlers":["default"]}]}}}
{"timestamp":"2015-03-05T15:49:39.670962+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:673:in `connect_server': invalid server or port (EventMachine::ConnectionError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:673:in `bind_connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:649:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:457:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp.rb:242:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:118:in `setup_connection'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:147:in `connect_with_eligible_options'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:14:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport.rb:22:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/daemon.rb:133:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:254:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:13:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:12:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'
```

**Comment by josegonzalez** [comment]
Mind making a PR?

**Comment by JamieCressey** [comment]
Closing due to inactivity. PRs are accepted - Feel free to reopen!
