### ISSUE TITLE
debugging issue with redis and queue

### ISSUE THREAD

**Issue by bilsch** [python-beaver/python-beaver#390]
Not sure if this is the best place to ask about this - feel free to bounce me to a better place.

I'm debugging an issue in the [run_queue.py](https://github.com/python-beaver/python-beaver/blob/master/beaver/run_queue.py#L34-L51) and have some questions.

What is the significance of [transports](https://github.com/python-beaver/python-beaver/blob/master/beaver/run_queue.py#L76-L77) and how does it relate to the queue size? Is this the same thing or somehow different?

```
[2016-02-01 10:35:07,545] DEBUG   Number of transports: 1000
[2016-02-01 10:35:07,545] DEBUG   Main consumer queue Size is: 0
```

I'm debugging an issue related to timeouts and redis. We were tripping the queue timeout which was previously at a very long 12 hours. I noticed large surges in log ingestion to our elk stack and tracked it back to something going on in how beaver is slurping the data in. When I shrank the timeout down to 600 seconds we ended up with this:

```
[2016-02-01 09:05:21,076] INFO    Starting queue consumer
[2016-02-01 09:15:24,076] INFO    Queue timeout of "600" seconds exceeded, stopping queue
[2016-02-01 09:15:26,127] INFO    Starting queue consumer
[2016-02-01 09:25:29,042] INFO    Queue timeout of "600" seconds exceeded, stopping queue
[2016-02-01 09:25:31,181] INFO    Starting queue consumer
[2016-02-01 09:35:34,050] INFO    Queue timeout of "600" seconds exceeded, stopping queue
[2016-02-01 09:35:36,241] INFO    Starting queue consumer
[2016-02-01 09:45:39,097] INFO    Queue timeout of "600" seconds exceeded, stopping queue
[2016-02-01 09:45:41,299] INFO    Starting queue consumer
[2016-02-01 09:55:44,029] INFO    Queue timeout of "600" seconds exceeded, stopping queue
[2016-02-01 09:55:46,351] INFO    Starting queue consumer
```

Where the queue is constantly restarting.

Any ideas on what to look at?

Beaver version: 36.0.0 and 36.0.1 - both show this problem
redis version: 3.0.5

beaver.conf:

```
[beaver]
redis_url = redis://xxxx.internal:6379/0
redis_namespace: logstash:beaver
queue_timeout: 600
logstash_version: 1
sincedb_path: /tmp/beaver_since.db
```

Not sure if the other input config sections would be related - I can post / describe those. Basically the typical tail a file pattern and ship it off with a few tags/fields.

**Comment by ltsampros** [comment]
We are looking at the same issue. We have generally tracked this down to when a file is removed. Then everything gets stuck for "queue_timeout" seconds after which we have a crash.

```
[2016-02-12 20:06:42,260] INFO    [/var/log/nginx/access.json] - watching logfile
[2016-02-12 20:06:42,262] INFO    [/var/log/auth.log] - watching logfile
[2016-02-12 20:06:42,262] INFO    [/var/log/syslog] - watching logfile
[2016-02-11 06:31:45,102] INFO    [/var/log/syslog] - file rotated
[2016-02-11 06:31:48,018] INFO    [/var/log/syslog] - watching logfile
[2016-02-11 07:57:44,774] WARNING cannot parse as rawjson: message
[2016-02-11 09:12:36,564] WARNING cannot parse as rawjson: message
[2016-02-11 16:59:12,099] INFO    [/var/lib/docker/containers/4c8a31f349906aca8571ac1075fa82708f56077fcd0d59cf9ca3a61969df080e/4c8a31f349906aca8571ac1075fa82708f56077fcd0d59cf9ca3a61969df080e-json.log] - file removed
[2016-02-11 17:59:14,711] INFO    Queue timeout of "3600" seconds exceeded, stopping queue
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beaver/dispatcher/tail.py", line 83, in create_queue_producer
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/beaver/worker/tail_manager.py", line 76, in run
    self._tails[fid].run(once=True)
  File "/usr/local/lib/python2.7/dist-packages/beaver/worker/tail.py", line 118, in run
    self._ensure_file_is_good(current_time=current_time)
  File "/usr/local/lib/python2.7/dist-packages/beaver/worker/tail.py", line 211, in _ensure_file_is_good
    fid = self.get_file_id(st)
UnboundLocalError: local variable 'st' referenced before assignment
```

**Comment by bilsch** [comment]
interesting @ltsampros I have not seen the crash.

So far dropping the timeout down to 10 minutes we at least don't get a giant surge in log traffic which is nice.

**Comment by gregsterin** [comment]
+1

This continues to exist in 36.2.

Problem is here:
https://github.com/python-beaver/python-beaver/blob/master/beaver/worker/tail.py#L211

If the file isn't there, then st never gets set, however the exception is handled, so st becomes an unassigned variable when it gets referenced, which seems like a bug to me.

Perhaps the function should just return after that point here?

https://github.com/python-beaver/python-beaver/blob/master/beaver/worker/tail.py#L209

**Comment by josegonzalez** [comment]
@gregsterin want to file a pull request?

**Comment by gregsterin** [comment]
@josegonzalez how does this look to you?

https://github.com/python-beaver/python-beaver/pull/413/files

**Comment by josegonzalez** [comment]
👍 I left a note

**Comment by gregsterin** [comment]
@josegonzalez 

"I left a note"

not seeing any comments on the PR?

**Comment by josegonzalez** [comment]
Ha the new review thing left it in an unsubmitted state :P

**Comment by JamieCressey** [comment]
Closing due to inactivity. Feel free to reopen!
