### ISSUE TITLE
Unable to install beaver as it depends on six and doesn't declare that it does depend on it

### ISSUE THREAD

**Issue by damm** [python-beaver/python-beaver#420]
It looks like we depend on six but it's not being installed via pip; and looking at the requirements/base.txt it's not listed.

 ```
      STDOUT: Collecting beaver from git+git://github.com/python-beaver/python-beaver.git@36.2.1#egg=beaver
         Cloning git://github.com/python-beaver/python-beaver.git (to 36.2.1) to /tmp/pip-build-yj1Lsc/beaver
       Requirement already satisfied: boto>=2.18.0 in /opt/beaver/lib/python2.7/site-packages (from beaver)
       Requirement already satisfied: conf_d>=0.0.4 in /opt/beaver/lib/python2.7/site-packages (from beaver)
       Collecting glob2==0.3 (from beaver)
         Downloading glob2-0.3.tar.gz
       Collecting kafka-python==0.9.5 (from beaver)
         Downloading kafka-python-0.9.5.tar.gz (73kB)
       Collecting paho-mqtt==1.1 (from beaver)
         Downloading paho-mqtt-1.1.tar.gz (41kB)
       Collecting msgpack-pure>=0.1.3 (from beaver)
         Downloading msgpack-pure-0.1.3.tar.gz
       Collecting pika>=0.9.14 (from beaver)
         Downloading pika-0.10.0-py2.py3-none-any.whl (92kB)
       Collecting python-daemon<=1.6.1,>=1.5.2 (from beaver)
         Downloading python-daemon-1.6.1.tar.gz (47kB)
       Collecting redis>=2.7.5 (from beaver)
         Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
       Collecting requests (from beaver)
         Downloading requests-2.17.3-py2.py3-none-any.whl (87kB)
       Collecting six (from kafka-python==0.9.5->beaver)
         Downloading six-1.10.0-py2.py3-none-any.whl
       Requirement already satisfied: setuptools in /opt/beaver/lib/python2.7/site-packages (from python-daemon<=1.6.1,>=1.5.2->beaver)
       Collecting lockfile>=0.9 (from python-daemon<=1.6.1,>=1.5.2->beaver)
         Downloading lockfile-0.12.2-py2.py3-none-any.whl
       Collecting idna<2.6,>=2.5 (from requests->beaver)
         Downloading idna-2.5-py2.py3-none-any.whl (55kB)
       Collecting urllib3<1.22,>=1.21.1 (from requests->beaver)
         Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
       Collecting chardet<3.1.0,>=3.0.2 (from requests->beaver)
         Downloading chardet-3.0.3-py2.py3-none-any.whl (133kB)
       Collecting certifi>=2017.4.17 (from requests->beaver)
         Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
       Installing collected packages: glob2, six, kafka-python, paho-mqtt, msgpack-pure, pika, lockfile, python-daemon, redis, idna, urllib3, chardet, certifi, requests, beaver
         Running setup.py install for glob2: started
           Running setup.py install for glob2: finished with status 'error'
           Complete output from command /opt/beaver/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yj1Lsc/glob2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gSa9ZU-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/beaver/include/site/python2.7/glob2:
           running install
           running build
           running build_py
           creating build
           creating build/lib.linux-x86_64-2.7
           creating build/lib.linux-x86_64-2.7/glob2
           copying src/glob2/impl.py -> build/lib.linux-x86_64-2.7/glob2
           copying src/glob2/fnmatch.py -> build/lib.linux-x86_64-2.7/glob2
           copying src/glob2/__init__.py -> build/lib.linux-x86_64-2.7/glob2
           running install_lib
           creating /opt/beaver/lib/python2.7/site-packages/glob2
           copying build/lib.linux-x86_64-2.7/glob2/impl.py -> /opt/beaver/lib/python2.7/site-packages/glob2
           copying build/lib.linux-x86_64-2.7/glob2/fnmatch.py -> /opt/beaver/lib/python2.7/site-packages/glob2
           copying build/lib.linux-x86_64-2.7/glob2/__init__.py -> /opt/beaver/lib/python2.7/site-packages/glob2
           byte-compiling /opt/beaver/lib/python2.7/site-packages/glob2/impl.py to impl.pyc
           byte-compiling /opt/beaver/lib/python2.7/site-packages/glob2/fnmatch.py to fnmatch.pyc
           byte-compiling /opt/beaver/lib/python2.7/site-packages/glob2/__init__.py to __init__.pyc
           running install_egg_info
           running egg_info
           writing src/glob2.egg-info/PKG-INFO
           writing top-level names to src/glob2.egg-info/top_level.txt
           writing dependency_links to src/glob2.egg-info/dependency_links.txt
           reading manifest file 'src/glob2.egg-info/SOURCES.txt'
           reading manifest template 'MANIFEST.in'
           writing manifest file 'src/glob2.egg-info/SOURCES.txt'
           Copying src/glob2.egg-info to /opt/beaver/lib/python2.7/site-packages/glob2-0.3-py2.7.egg-info
           running install_scripts
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-yj1Lsc/glob2/setup.py", line 40, in <module>
        package_dir = {'': 'src'},
             File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
             File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
             File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
             File "/opt/beaver/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
             File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run
        self.run_command(cmd_name)
             File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
             File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
             File "/opt/beaver/local/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 17, in run
        import setuptools.command.easy_install as ei
             File "/opt/beaver/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 49, in <module>
        from setuptools.py27compat import rmtree_safe
             File "/opt/beaver/local/lib/python2.7/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
           ImportError: No module named six
```

**Comment by josegonzalez** [comment]
I don't depend on six, setuptools does. You may wish to look at the version of setuptools you installed, as I believe they did some weird refactorings recently regarding `six`.

**Comment by damm** [comment]
It's delivered via a chef cookbook; so I'm guessing it has to do with how they install pip.  Why is six in the other requirements file if you don't depend on it?

**Comment by josegonzalez** [comment]
It's just in tests.

Anyhow, this is your [bug](https://github.com/pypa/setuptools/issues/1042). You're using an unpinned setuptools, so it probably grabbed the transiently broken setuptools. Try it again with latest setuptools and it should be fine.

**Comment by damm** [comment]
Nah it's installed actually by the poise-python cookbook which uses https://bootstrap.pypa.io/get-pip.py to install it.

Updated the cookbook against my beaver cookbook and it installs fine; so I must be shipping an older version of poise-python internally that's running broken setuptools by default.
