### ISSUE TITLE
beaver is incompatible with pika version 1.0.1

### ISSUE THREAD

**Issue by amvapor** [python-beaver/python-beaver#435]
When using pika v1.0.1 beaver outputs the following errors:
```
sh-4.2# /usr/bin/beaver -c /etc/beaver/beaver.conf -C /etc/beaver/conf.d
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/site-packages/beaver/run_queue.py", line 25, in run_queue
    transport = create_transport(beaver_config, logger=logger)
  File "/usr/lib64/python2.7/site-packages/beaver/transports/__init__.py", line 20, in create_transport
    transport = transport_class(beaver_config=beaver_config, logger=logger)
  File "/usr/lib64/python2.7/site-packages/beaver/transports/rabbitmq_transport.py", line 34, in __init__
    self._connect()
  File "/usr/lib64/python2.7/site-packages/beaver/transports/rabbitmq_transport.py", line 146, in _connect
    socket_timeout=self._rabbitmq_config['timeout']
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 643, in __init__
    self.ssl_options = ssl_options
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 491, in ssl_options
    'ssl_options must be None or SSLOptions but got %r' % (value,))
TypeError: ssl_options must be None or SSLOptions but got {'ca_certs': None, 'certfile': None, 'keyfile': None, 'ssl_version': 3}
```

when switched to pika 0.12.0, Beaver runs fine.

I believe the following lines require a minor refactoring to support Pika's updated API

https://github.com/python-beaver/python-beaver/blob/master/beaver/transports/rabbitmq_transport.py#L153-L166

**Comment by josegonzalez** [comment]
Pull requests welcome!

**Comment by wdoekes** [comment]
I know this is old, but I landed here by accident.

Relevant changes: https://github.com/pika/pika/commit/eecbb8ce38d87cf8df569c625cd3b23acc05bec1

Example of compatible code: https://github.com/ossobv/vendor/blob/f402acbd3f1edab66077e66006711297286d66ab/osso_ez_rmq.py#L38-L61
